# Este archivo es solo para referencia y debe ser configurado en Streamlit Cloud
# No subir este archivo al repositorio con credenciales reales

[general]
# Configuraci贸n de OpenAI
OPENAI_API_KEY = "tu-api-key-de-openai"

# Configuraci贸n de Pinecone
PINECONE_API_KEY = "tu-api-key-de-pinecone" 
PINECONE_ENVIRONMENT = "us-east-1"
PINECONE_INDEX_NAME = "timbre"

# Opcional: Configuraci贸n de email para el buz贸n de observaciones
EMAIL_REMITENTE = "tu-email@example.com"
EMAIL_DESTINATARIO = "tu-email@example.com"
EMAIL_PASSWORD = "tu-password"

# Opcional: Otras configuraciones
LANGCHAIN_API_KEY = "tu-api-key-de-langchain"
TAVILY_API_KEY = "tu-api-key-de-tavily" 